### PR TITLE
Distinguish rush! release builds from development builds

### PR DESCRIPTION
**Pull request by frenzibyte**
- [x] Depends on https://github.com/ppy/osu/pull/12259
- [x] Depends on game bump

This is done for the sole reason of being able to load a development rush! build side by side with an official release build, for comparing things between pretty quickly and identify bugs without having to resort to exiting the game, switching to master, etc..

image

Builds generated by CI through artifacts now use a special configuration named `Development`, which is optimized like your usual release config, but falls down within the development builds.

- In the above image, the ruleset displayed description below the selector button is rather unfortunate, but can't be helped within our scope.

### CODE REVIEW

**Comment by frenzibyte** [comment]
Definitely cared about that, but for some reason it straight up doesn't work, haven't digged through the reason yet, but you can give it a try yourself if it's possible to do.

**Comment by LumpBloom7** [comment]
I've pushed the change I've suggested earlier, and also added the appropriate tasks for vscode.

However, while the dev build is being shown with a different icon, the release build placed in my rulesets folder doesn't show up at all. Surely that shouldn't be the case right? (tested with vscode and VS)

**Comment by swoolcock** [comment]
Surely they need to also have different namespaces?

**Comment by frenzibyte** [comment]
> Surely they need to also have different namespaces?

Don't think that's possible to do on all classes, hence why I'm afraid from just changing `RootNamespace`. It's still working fine for me either way, the instantiation info of the ruleset differs based on the assembly name, so nothing to worry osu!lazer-side as well.

**Review by LumpBloom7 — APPROVED** [review]
If there's nothing else needed, then this looks good to me.

**Pull request merged**
