### PR TITLE
Implement fever mode

### LINKED ISSUE #30: Fever mode
Requirements:

* Fever bar, builds up based on judgment accuracy
* Automatic/manual triggering (toggleable in ruleset config)
* Lasts for ~10 seconds when triggered
* Large score multiplier while active
* Should be obvious when the fever bar is full, and while fever mode is active

### PR DESCRIPTION
**Pull request by LumpBloom7**
Resolves #30

This PR implements a working fever mode into gameplay. Fever takes 100 GREAT hits to fill, or 152 GOOD hits. Fever lasts for 5 seconds on activation.

Currently fever is only activated via an explicit action. I've decided to leave out automatic fever for now, as the implementation of that requires the modification of other systems to support it.

### FeverTracker
The `FeverTracker` is responsible for handling the backing fever state, including the progress and activation states. Hitting notes will notify the tracker via `OnNewResult`, and the meter will fill a certain amount based on the judgement obtained. (Bonus and IgnoreJudgement aren't considered)

During rewind, the tracker uses `OnRevertResult` to revert the meter to the state before the judgement. Extra information about when the player triggered fever is stored, and is used to ensure that fever states are properly reverted or corrected during rewind.

Transforms are used to drain the meter during fever, and will automatically deactivate fever when the meter is emptied. During fever, new results or reverts will not be considered.

### FeverBar
This is a UI element that gives the player an indication of fever progress and activation state. It binds to FeverTracker, and will respond to changes to the fever states.

### CODE REVIEW

**Comment by swoolcock** [comment]
Looks good, we might even want to do some fancy background animations in future.  Great stuff.  :)

**Comment by HeyItsJinx** [comment]
> Looks good, we might even want to do some fancy background animations in future. Great stuff. :)

I know its a very early development thing but please make a fancy background animation optional for players. 

Sometimes its just there to make stuff harder to read

**Comment by swoolcock** [comment]
Yeah of course, but it would be enabled by default.

**Review by frenzibyte — APPROVED** [review]
Pretty great 👍🏻 

Unfortunate the `FeverProcessor` had to go through some rewinding logic and sane state resetting in order to work properly, but... let's just merge this and fix it later on with a fresh mind if it ever becomes an issue.

**Pull request merged**
